# This file was automatically generated by alf
# https://github.com/dannyben/alf

unalias g 1>/dev/null 2>&1
g() {
  case "$1" in
    s)
      shift
      git status "$@"
      ;;
    deploy)
      shift
      docker stack deploy "$@"
      ;;
    *)
      git "$@"
      ;;
  esac
}

unalias dns 1>/dev/null 2>&1
dns() {
  case "$1" in
    check)
      shift
      host -t ns "$@"
      ;;
    *)
      echo this alias requires a subcommand
      ;;
  esac
}

# Completions
if command -v complete &> /dev/null ; then
  complete -W "s deploy" g
  complete -W "check" dns
fi
