#!/usr/bin/env bash
# Run this from the main repo directory

cd ./test
source "approvals.bash"

if [[ $TEST ]]; then
  "./${TEST}_spec.sh"
else
  for file in *_spec.sh ; do
    context "$file"
    "./$file" || fail "aborted test loop"
  done
fi
