#!/usr/bin/env zsh
# Run this from the main repo directory

source 'test/approvals.bash'

unset ALF_RC_FILE
export ALF_ALIASES_FILE="aliases.txt"

context "in zsh"
  describe "generated aliases in zsh"
    pushd test/fixtures/generate > /dev/null
    rm -f "aliases.txt"
    approve "alf save"
    source 'aliases.txt' || return 0
    approve "say again zsh-works"
    popd

green "\nSanity test on ZSH passed!"