#!/usr/bin/env bash
# ---------------------------------------------------------------
# Alf - Your Little Bash Alias Friend
# ---------------------------------------------------------------
usage() { 
  if $LONG_USAGE; then
    printf "alf $VERSION - Your Little Bash Alias Friend\n\n"
  fi
  printf "Usage:\n"
  printf "  alf connect REPO\n"
  if $LONG_USAGE; then
    printf "    Connect to a remote git repository.\n"
    printf "    REPO can be:\n"
    printf "    - Your username on GitHub. In this case, we will assume the\n"
    printf "      repository is named 'alf-config'\n"
    printf "    - Your username/repo on GitHub\n"
    printf "    - Any other full URL to a repository\n\n"
  fi
  printf "  alf download\n"
  if $LONG_USAGE; then
    printf "    Perform 'git pull' on a previously connected repo\n\n"
  fi
  printf "  alf upload\n"
  if $LONG_USAGE; then
    printf "    Perform 'git commit' and 'git push' on a previously connected\n"
    printf "    repo\n\n"
  fi
  printf "  alf generate\n"
  if $LONG_USAGE; then
    printf "    Generate aliases from the config file in the connected repo\n"
    printf "    to stdout\n\n"
  fi
  printf "  alf save\n"
  if $LONG_USAGE; then
    printf "    Generate aliases and save to ~/.bash_aliases\n\n"
  fi
  printf "  alf -h|--help\n"
  if $LONG_USAGE; then
    printf "    Show this message\n\n"
  fi
  printf "  alf -v|--version\n"
  if $LONG_USAGE; then
    printf "    Show version number\n\n"
  fi
}

find_config() {
  CONFIG_FILE="alf.conf"
  REPO_PATH="$PWD/alf-conf"
  if [[ -f $RC_FILE ]]; then
    REPO_PATH=$(<$RC_FILE)
    CONFIG_FILE=$REPO_PATH/alf.conf
  fi
}

generate_last_cmd() {
  if [[ -n $lastcmd ]]; then
    if [[ $cond = "if" ]]; then
      echo "  $lastcmd \"\$@\""
      echo "}"
    else
      echo "  else"
      echo "    $lastcmd \"\$@\""
      echo "  fi"
      echo "}"
      cond="if"
    fi
  fi
}

generate() {
  regex="^(\s*)([a-z\-]+):\s*(.+)$"
  cond="if"
  lastcmd=""
  find_config

  while IFS= read -r line; do
    if [[ $line =~ $regex ]]; then
      indent="${BASH_REMATCH[1]}"
      
      if [[ -z $indent ]]; then
        ali1="${BASH_REMATCH[2]}"
        cmd1="${BASH_REMATCH[3]}"
        unset ali2
        unset cmd2
        generate_last_cmd
        lastcmd=$cmd1
      else
        ali2="${BASH_REMATCH[2]}"
        cmd2="${BASH_REMATCH[3]}"
      fi    

      if [[ -n $ali2 ]]; then
        echo "  $cond [[ \$1 = \"$ali2\" ]]; then"
        echo "    shift"
        echo "    $cmd1 $cmd2 \"\$@\""
        cond="elif"
      else
        echo ""
        echo "$ali1() {"
      fi
    fi
  done < $CONFIG_FILE
  generate_last_cmd
}

make_full_repo_path() {
  if [[ $REPO =~ ':' ]]; then
    REPO_URL=$REPO
  elif [[ $REPO =~ '/' ]]; then
    REPO_URL="https://github.com/$REPO.git"
  else
    REPO_URL="https://github.com/$REPO/alf-conf.git"
  fi
}

download() {
  find_config
  if [[ ! -f $RC_FILE ]]; then
    echo "Cannot find $RC_FILE"
    echo "Please connect alf to a repository first"
    exit 1
  fi
  pushd $REPO_PATH > /dev/null
  echo "Pulling from repository to $REPO_PATH"
  git pull
  popd > /dev/null
  $ME save
}

upload() {
  find_config
  if [[ ! -f $RC_FILE ]]; then
    echo "Cannot find $RC_FILE"
    echo "Please connect alf to a repository first"
    exit 1
  fi
  pushd $REPO_PATH > /dev/null
  echo "Pushing $REPO_PATH to repository"
  git commit -am "automatic push"
  git push
  popd > /dev/null
}

connect() {
  make_full_repo_path
  echo "This operation will:"
  if [[ ! -d ./alf-conf ]]; then
    echo "  clone  $REPO_URL"
    echo "     to  ./alf-conf"
  fi
  echo "  write  $PWD/alf-conf"
  echo "     to  $RC_FILE"
  echo ""
  printf "Continue? [yN] "
  read answer
  if [[ $answer =~ [Yy] ]]; then
    if [[ -d ./alf-conf ]]; then
      echo "Skipping clone, directory already exists"
    else
      git clone $REPO_URL ./alf-conf
    fi
    echo "$PWD/alf-conf" > "$RC_FILE"
    echo "Storing location in $RC_FILE"
  else
    echo "Aborting"
    exit
  fi
  $ME save
}

save() {
  echo "Saving to ~/.bash_aliases"
  $ME generate > ~/.bash_aliases
}

main() {
  # internal variables
  VERSION="0.0.1"
  LONG_USAGE=false
  REPO=''
  RC_FILE=~/.alfrc
  ME=$0

  # execute
  set -e
  case "$1" in
    c | connect  ) REPO=$2; connect ;;
    d | download ) download ;;
    g | generate ) generate ;;
    s | save     ) save ;;
    u | upload   ) upload ;;
    -h | --help    | help    ) LONG_USAGE=true; usage ;;
    -v | --version | version ) echo $VERSION ;;
    * ) usage ;;
  esac
}

if ! $ALF_SUPRESS_RUN; then
  main $@
fi
