#!/usr/bin/env bash
# ---------------------------------------------------------------
# fung - generate bash aliases (as functions) from config.
# 
# Usage:
# $ ./fungen config > ~/.bash_aliases && . ~/.bash_aliases
#
# See the sample config file for more details
# ---------------------------------------------------------------

function generate_last_cmd {
  if [[ -n $lastcmd ]]; then
    if [[ $cond = "if" ]]; then
      echo "  $lastcmd \"\$@\""
      echo "}"
    else
      echo "  else"
      echo "    $lastcmd \"\$@\""
      echo "  fi"
      echo "}"
      cond="if"
    fi
  fi
}

regex="^(\s*)([a-z\-]+):\s*(.+)$"
cond="if"
lastcmd=""

echo "#!/usr/bin/env bash"

while IFS= read -r line; do
  if [[ $line =~ $regex ]]; then
    indent="${BASH_REMATCH[1]}"
    
    if [[ -z $indent ]]; then
      ali1="${BASH_REMATCH[2]}"
      cmd1="${BASH_REMATCH[3]}"
      unset ali2
      unset cmd2
      generate_last_cmd
      lastcmd=$cmd1
    else
      ali2="${BASH_REMATCH[2]}"
      cmd2="${BASH_REMATCH[3]}"
    fi    

    if [[ -n $ali2 ]]; then
      echo "  $cond [[ \$1 = \"$ali2\" ]]; then"
      echo "    shift"
      echo "    $cmd1 $cmd2 \"\$@\""
      cond="elif"
    else
      echo ""
      echo "function $ali1 {"
    fi
  fi
done < "${1:-/dev/stdin}"
generate_last_cmd

