#!/usr/bin/env bash

# Figure out if we need sudo or not
sudo=''
if [[ $EUID -ne 0 ]]; then
  sudo='sudo'
fi

# Banner function
banner() {
  green='\033[1;32m'
  reset='\033[0m'
  echo -e "\n=== ${green}${1}${reset}"
}

# Prepare a temp directory
temp_dir=$(mktemp -d)
pushd "$temp_dir" > /dev/null
banner "Cloning git repository (in ${temp_dir})"
git clone --depth=1 https://github.com/DannyBen/alf.git .

banner "Copying executable to /usr/local/bin/alf"
$sudo install -m 755 alf /usr/local/bin/

banner "Copying man pages to /usr/local/bin/alf"
for file in doc/*.1; do
  $sudo cp "$(realpath "$file")" /usr/share/man/man1/;
done

popd > /dev/null

# Verify
if type alf >/dev/null; then
  banner "Done. Type 'alf --help' for more info."
else
  banner "Setup failed."
  exit 1
fi

