# This file was automatically generated by alf
# https://github.com/dannyben/alf

unalias git 1>/dev/null 2>&1
git() {
  command git "$@"
}

unalias reverse 1>/dev/null 2>&1
reverse() {
  echo $2 $1
}
