# This file was automatically generated by alf
# https://github.com/dannyben/alf

unalias G 1>/dev/null 2>&1
G() {
  case "$1" in
    S)
      shift
      git status "$@"
      ;;
    DEPLOY)
      shift
      docker stack deploy "$@"
      ;;
    *)
      git "$@"
      ;;
  esac
}

unalias DNS 1>/dev/null 2>&1
DNS() {
  case "$1" in
    CHECK)
      shift
      host -t ns "$@"
      ;;
    *)
      dig +short "$@"
      ;;
  esac
}

# Completions
if command -v complete &> /dev/null ; then
  complete -W "S DEPLOY" G
  complete -W "CHECK" DNS
fi
