name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install test dependencies
      run: sudo apt-get update && sudo apt-get install -y bats shellcheck
    - name: Run shellcheck tests
      run: shellcheck alf setup uninstall test/test_helper.bash
    - name: Run Bats tests
      run: bats --recursive --print-output-on-failure test

  ubuntu_setup:
    name: Setup on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run setup
      run:
        ./setup
        command -v alf
    - name: Run uninstall
      run:
        ./uninstall
        ! command -v alf

  macos_setup:
    name: Setup on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Upgrade the outdated bash
      run: brew install bash
    - name: Run setup
      run:
        ./setup
        command -v alf
    - name: Run uninstall
      run:
        ./uninstall
        ! command -v alf
